@url = http://localhost:5000
@productId = f3c5fbf0-fea3-41e5-96dd-e5f672b444fb
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxZTIyMDVjMy1lY2EzLTRjZWUtYTY0Ny00ODI1Y2ZiNjcwNDciLCJ1bmlxdWVfbmFtZSI6IjFlMjIwNWMzLWVjYTMtNGNlZS1hNjQ3LTQ4MjVjZmI2NzA0NyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6InVzZXIiLCJuYmYiOjE1MjkyMTkzNzUsImV4cCI6MTUyOTIxOTY3NSwiaXNzIjoibXlzdG9yZSJ9.gNxJZb5-4cnU-JeTTeWIDIUoEjfkO50Mp-hc9eEjd6c

###
GET {{url}}/products

###
GET {{url}}/products/{{productId}}

###
POST {{url}}/products
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "My product",
    "category": "products",
    "price": 2000
}

###
POST {{url}}/sign-up
Content-Type: application/json

{
    "username": "user",
    "password": "secret"
}

###
POST {{url}}/sign-in
Content-Type: application/json

{
    "username": "user",
    "password": "secret"
}

###
GET {{url}}/me
Authorization: Bearer {{token}}