@url = http://localhost:5000
@productId = f3c5fbf0-fea3-41e5-96dd-e5f672b444fb
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiYzdlZWQ1Ny1lOWIwLTQxMWEtOTYxMi02NzY1MTgwYzExZTUiLCJ1bmlxdWVfbmFtZSI6ImJjN2VlZDU3LWU5YjAtNDExYS05NjEyLTY3NjUxODBjMTFlNSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6ImFkbWluIiwibmJmIjoxNTI5MjIzNDA5LCJleHAiOjE1MjkyMjM3MDksImlzcyI6Im15c3RvcmUifQ.vf_swAtdETQ2slWxLOrBzHahqN5sDlnX-hqLx9927Rk

###
GET {{url}}/products

###
GET {{url}}/products/{{productId}}

###
POST {{url}}/products
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "My product",
    "category": "products",
    "price": 2000
}

###
POST {{url}}/sign-up
Content-Type: application/json

{
    "username": "admin",
    "password": "secret",
    "role": "admin"
}

###
POST {{url}}/sign-in
Content-Type: application/json

{
    "username": "admin",
    "password": "secret"
}

###
GET {{url}}/me
Authorization: Bearer {{token}}