@url = http://localhost:5000
@productId = a6c204b6-be7a-4239-a820-d4b6d1d56a2b

###
GET {{url}}/products

###
GET {{url}}/products/{{productId}}

###
POST {{url}}/products
Content-Type: application/json

{
    "name": "My product",
    "category": "products",
    "price": 2000
}